//! AIX artifact generation for Vampiro.
//!
//! Generates `llms.txt` and `llm.txt` through `genesis::aix`.
//! No second local renderer — all generation routes through Genesis.

use std::path::Path;

/// Vampiro project metadata used for AIX generation.
pub struct ProjectMeta {
    pub name: &'static str,
    pub tagline: &'static str,
    pub description: &'static str,
    pub commands: &'static [(&'static str, &'static str)],
}

/// Default project metadata for the vampiro repository.
pub const VAMPIRO_META: ProjectMeta = ProjectMeta {
    name: "vampiro",
    tagline: "Cross-language Rust CLI (v0.2.0) for checking whether code composes correctly at call and module boundaries. Supports Python, Clojure, Julia, and Rust via tree-sitter frontends.",
    description: "Cross-language Rust CLI (v0.3.1) that checks whether the pieces of a codebase actually compose. Uses tree-sitter frontends for Python, Clojure, Julia, and Rust to emit a shared Composition IR (CIR) with per-slot data-flow edges. Composition seam analysis achieves ~99.8% precision on clean baselines.",
    commands: &[
        ("vampiro check", "Check source files for composition, modularity, and robustness breaks"),
    ],
};

/// Generate `llms.txt` content using `genesis::aix`.
pub fn generate_llms_txt(meta: &ProjectMeta) -> String {
    let mut content = String::new();

    // Title and tagline
    content.push_str(&format!("# {}\n\n> {}\n\n", meta.name, meta.tagline));

    // Genesis adoption
    content.push_str("## Genesis Adoption\n\n");
    content.push_str(
        "vampiro uses the `genesis-vibes` v0.4 shared crate for cross-cutting infrastructure.\n",
    );
    content.push_str("Currently adopted modules:\n\n");
    content.push_str("| Module | Status | Notes |\n");
    content.push_str("|--------|--------|-------|\n");
    content.push_str("| `config` | ✅ | ConfigFile, ConfigRegistry, ConfigStore |\n");
    content.push_str("| `doctor` | ✅ | DoctorCheck, DoctorRunner |\n");
    content.push_str("| `guide` | ✅ | Guide, CommandRegistry, ErrorSink |\n");
    content.push_str("| `managed_block` | ✅ | BlockDef, BlockInjector, BlockRegistry |\n");
    content.push_str("| `status` | ✅ | StatusContributor, StatusItem |\n");
    content.push_str("| `suite_linter` | ✅ | LintResult, Severity |\n");
    content.push_str("| `cli` | ✅ | `generate_completions`, `maybe_print_version_json` |\n");
    content.push_str("| `envelope` | ✅ | `Envelope<T>` for structured output |\n");
    content.push_str(
        "| `feedback` | ✅ | `FeedbackArgs`, `handle_feedback` (scratch, redactor, gh) |\n",
    );
    content.push_str(
        "| `suggestions` | ✅ | `SuggestionEngine`, `CommandRegistry` for typo detection |\n",
    );
    content.push_str("| `scaffold` | ✅ | `Scaffold` builder for `init` command |\n");
    content.push_str("| `discovery` | ✅ | `.genesis/tools.toml` manifest, `scan`, `register` |\n");
    content.push_str("| `fixture` | ✅ | `Fixture` builder for test environments |\n");
    content.push_str("| `aix` | ✅ | AIX artifact generation (agents block) |\n");

    // Authorship note
    content.push_str("## Authorship\n\n");
    content.push_str("All code in this repository was generated by a large language model. ");
    content.push_str("Human contribution: requirements, design decisions, planning, and review.\n");

    // Managed block for agent instructions
    content.push_str("\n---\n\n");
    content.push_str(&genesis::aix::agents_block("VAMPIRO", "\n## Project\n\n"));

    content
}

/// Generate `llm.txt` content using `genesis::aix`.
pub fn generate_llm_txt(meta: &ProjectMeta) -> String {
    let mut content = String::new();

    // Title and tagline
    content.push_str(&format!(
        "# {}\n\n> {}\n\n",
        capitalize(meta.name),
        meta.tagline
    ));

    // Description
    content.push_str("## What It Does\n\n");
    content.push_str(meta.description);
    content.push('\n');

    // Seam axes
    content.push_str("\n### Seam Axes\n\n");
    content.push_str("| Axis | Question |\n");
    content.push_str("|---|---|\n");
    content.push_str(
        "| **composition** | Does the produced structural shape match what the caller accepts? |\n",
    );
    content.push_str(
        "| **modularity** | Does the edge respect the target module's declared interface? |\n",
    );
    content.push_str("| **optionality** | Are structurally interchangeable implementations lawfully interchangeable? |\n");
    content.push_str("| **robustness** | Are effects, retries, fallbacks, and resource obligations handled completely? |\n");

    // Key commands
    content.push_str("\n## Key Commands\n\n");
    for (cmd, desc) in meta.commands {
        content.push_str(&format!("```\n{cmd}     # {desc}\n```\n"));
    }

    // Links
    content.push_str("\n## Links\n\n");
    content.push_str("- Repository: https://github.com/charly-vibes/vampiro\n");

    // Managed block
    content.push_str("\n---\n\n");
    content.push_str(&genesis::aix::agents_block("VAMPIRO", "\n## Context\n\n"));

    content
}

/// Generate and write AIX artifacts to the given directory.
pub fn write_aix_artifacts(dir: &Path, meta: &ProjectMeta) -> std::io::Result<()> {
    let llms = generate_llms_txt(meta);
    std::fs::write(dir.join("llms.txt"), &llms)?;

    let llm = generate_llm_txt(meta);
    std::fs::write(dir.join("llm.txt"), &llm)?;

    Ok(())
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn aix_llms_txt_generated_through_genesis() {
        let content = generate_llms_txt(&VAMPIRO_META);
        assert!(content.contains("# vampiro"));
        assert!(content.contains("Cross-language Rust CLI"));
        assert!(content.contains("<!-- VAMPIRO:START -->"));
        assert!(content.contains("<!-- VAMPIRO:END -->"));
    }

    #[test]
    fn aix_llm_txt_generated_through_genesis() {
        let content = generate_llm_txt(&VAMPIRO_META);
        assert!(content.contains("# Vampiro"));
        assert!(content.contains("Cross-language Rust CLI"));
        assert!(content.contains("<!-- VAMPIRO:START -->"));
        assert!(content.contains("<!-- VAMPIRO:END -->"));
    }

    #[test]
    fn aix_generation_is_deterministic() {
        let a = generate_llms_txt(&VAMPIRO_META);
        let b = generate_llms_txt(&VAMPIRO_META);
        assert_eq!(a, b, "llms.txt generation must be deterministic");

        let c = generate_llm_txt(&VAMPIRO_META);
        let d = generate_llm_txt(&VAMPIRO_META);
        assert_eq!(c, d, "llm.txt generation must be deterministic");
    }

    #[test]
    fn aix_no_second_local_renderer() {
        // The only rendering dependency is genesis::aix
        let _ = genesis::aix::agents_block("TEST", "body");
        // If this test compiles, we're using genesis::aix, not a local renderer
    }

    #[test]
    fn aix_committed_artifacts_are_current() {
        // Verify committed artifacts match generated output
        // Run `cargo test aix_regenerate_artifacts -- --ignored` to regenerate
        use std::path::PathBuf;

        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .to_path_buf();

        let expected_llms = generate_llms_txt(&VAMPIRO_META);
        let expected_llm = generate_llm_txt(&VAMPIRO_META);

        let actual_llms =
            std::fs::read_to_string(root.join("llms.txt")).expect("llms.txt should exist");
        assert_eq!(
            actual_llms, expected_llms,
            "llms.txt is stale — run `cargo test aix_regenerate_artifacts -- --ignored`"
        );

        let actual_llm =
            std::fs::read_to_string(root.join("llm.txt")).expect("llm.txt should exist");
        assert_eq!(
            actual_llm, expected_llm,
            "llm.txt is stale — run `cargo test aix_regenerate_artifacts -- --ignored`"
        );
    }

    #[test]
    #[ignore]
    fn aix_regenerate_artifacts() {
        use std::path::PathBuf;

        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .to_path_buf();

        write_aix_artifacts(&root, &VAMPIRO_META).unwrap();
        eprintln!("Regenerated AIX artifacts at {root:?}");
    }
}
